### ISSUE TITLE
Roadmap!

### ISSUE THREAD

**Issue by temp3l** [redcap3000/crypto-socket#1]
Hi,
Thanks for sharing your code!!! 

## Whats your plan for the project?

* did you see [cryptox](https://cryptox.pl) ? 
>cryptox manages API communication with different exchanges and provides common methods for all exchanges. Differences between the different API's are abstracted away.

* **Not** having to deal with API-differences made me choose cryptox for REST & Static part!
* just reviewed their code and must admit: very clean, lots of tests and Mockups!
* Schemas in ./test/helpers/jsonschemas.js !

* Would it make sense *for you* to reuse their abstraction-layer and data-structure here?
* Might save plenty of time debugging the clients!
* And again: when implementing the databases!

* It might also attract more ppl and even promote something like a 'Standard' ?
* I've only spent time with the poloniex API so far, so I cannot judge the other exchanges!

Converting the mostly_array-based realtime data into 'cryptox-objects' is a very small downgrade 
compared to debugging foreign exchange-APIs over and over again...
So crypto-socket might leave the data-abstraction part to some 'shared' modules and focus on awesome sockets ?

Let me know ;) 
Enjoy!

**Comment by redcap3000** [comment]
Yes I peeked at cryptox ... it does a lot more, but this project was only intended to be for ticker quotes only (to keep it simple.) It would not make sense to reuse it. This module is not intended to be designed to handle storage of the quote (only connection to the websocket and the data itself.) 

I am working on a larger private project that has trading/transfer capabilities, and while this module is a major component, its a very small one.

'Converting mostly array based to objects -' a downgrade? Not sure what you mean. There is so little data the structure is not as important. A simple memory based key-value store is perfectly fine for under 1024 values. This repo is a collection of the various methods one can connect to a websocket feed in node (as outlined per each exchanges' api instructions) 

Poloniex is not a good example of an API to follow. There are many different types of exchange API's so each one must be handled differently and (in the end) handle a 'final' code conversion in and out. For example, Poloniex refers to 'BTC_USDT' while other exchanges might follow "USDT_BTC" while other exchanges won't support USDT, so it will be USD. I believe the 'standard' (which I'm not familiar with.) is the cryptsy api (but is it a good idea to reuse a standard from a dead exchange?)

Promoting a 'standard' is thankless work... while Ideal it would not be polite to tell other programmers that their work is crap and will eventually lead to mass miss calculations that will eventually snowball into an amount that you can't do anything but figure out an excuse. It feels like in finance the developers in place have no real interest in changing what they have put into place.... 

There isn't even a solid place to go to get a basic run down on what markets are available on what exchange, minimum values, the sorts of things that traders care about on some of the largest API's (I'm looking at you Poloniex) .... and then documentation for use of API's of most exchanges are so terrible you're better off not using the exchange programatically. I think the management of this information, with regular updating, is probably the most important thing that needs to occur at this point.
