### ISSUE TITLE
Output to mysql

### ISSUE THREAD

**Issue by p0ntsNL** [redcap3000/crypto-socket#5]
Hi,

I would love to be able to put all the public ticker data into a mysql database.

Any thoughts on that?

**Comment by redcap3000** [comment]
Use the output from echoExchange() to insert/update records in your mysql database. Honestly I haven't used mysql in about 10 years so its not a priority. This library is not meant to store any data. You're more than welcome to create a pull request for this feature.

**Comment by slidenerd** [comment]
Can you do this using a socket-io client instead of pusher?

**Comment by redcap3000** [comment]
You could implement the mysql client in test.js loop to form and insert the data per specified interval inside a callback. Storing as json would probably be the simplest to avoid a complicated schema.

`setInterval(
  function(){
            cryptoSocket.echoExchange()
            mySQL('INSERT '\blablah stuff I dont remember' +  JSON.encode(cryptoSocket.Exchanges))                
},1000
);`
